# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vetas/Development/chapp/client_common

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vetas/Development/chapp/client_common

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vetas/Development/chapp/client_common/CMakeFiles /Users/vetas/Development/chapp/client_common/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vetas/Development/chapp/client_common/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client_common

# Build rule for target.
client_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_common
.PHONY : client_common

# fast build rule for target.
client_common/fast:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/build
.PHONY : client_common/fast

AesEncoder.o: AesEncoder.cpp.o

.PHONY : AesEncoder.o

# target to build an object file
AesEncoder.cpp.o:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/AesEncoder.cpp.o
.PHONY : AesEncoder.cpp.o

AesEncoder.i: AesEncoder.cpp.i

.PHONY : AesEncoder.i

# target to preprocess a source file
AesEncoder.cpp.i:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/AesEncoder.cpp.i
.PHONY : AesEncoder.cpp.i

AesEncoder.s: AesEncoder.cpp.s

.PHONY : AesEncoder.s

# target to generate assembly for a file
AesEncoder.cpp.s:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/AesEncoder.cpp.s
.PHONY : AesEncoder.cpp.s

Client.o: Client.cpp.o

.PHONY : Client.o

# target to build an object file
Client.cpp.o:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/Client.cpp.o
.PHONY : Client.cpp.o

Client.i: Client.cpp.i

.PHONY : Client.i

# target to preprocess a source file
Client.cpp.i:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/Client.cpp.i
.PHONY : Client.cpp.i

Client.s: Client.cpp.s

.PHONY : Client.s

# target to generate assembly for a file
Client.cpp.s:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/Client.cpp.s
.PHONY : Client.cpp.s

Command.o: Command.cpp.o

.PHONY : Command.o

# target to build an object file
Command.cpp.o:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/Command.cpp.o
.PHONY : Command.cpp.o

Command.i: Command.cpp.i

.PHONY : Command.i

# target to preprocess a source file
Command.cpp.i:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/Command.cpp.i
.PHONY : Command.cpp.i

Command.s: Command.cpp.s

.PHONY : Command.s

# target to generate assembly for a file
Command.cpp.s:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/Command.cpp.s
.PHONY : Command.cpp.s

Connection.o: Connection.cpp.o

.PHONY : Connection.o

# target to build an object file
Connection.cpp.o:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/Connection.cpp.o
.PHONY : Connection.cpp.o

Connection.i: Connection.cpp.i

.PHONY : Connection.i

# target to preprocess a source file
Connection.cpp.i:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/Connection.cpp.i
.PHONY : Connection.cpp.i

Connection.s: Connection.cpp.s

.PHONY : Connection.s

# target to generate assembly for a file
Connection.cpp.s:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/Connection.cpp.s
.PHONY : Connection.cpp.s

DiffieHellmanCalcSharedKey.o: DiffieHellmanCalcSharedKey.cpp.o

.PHONY : DiffieHellmanCalcSharedKey.o

# target to build an object file
DiffieHellmanCalcSharedKey.cpp.o:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/DiffieHellmanCalcSharedKey.cpp.o
.PHONY : DiffieHellmanCalcSharedKey.cpp.o

DiffieHellmanCalcSharedKey.i: DiffieHellmanCalcSharedKey.cpp.i

.PHONY : DiffieHellmanCalcSharedKey.i

# target to preprocess a source file
DiffieHellmanCalcSharedKey.cpp.i:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/DiffieHellmanCalcSharedKey.cpp.i
.PHONY : DiffieHellmanCalcSharedKey.cpp.i

DiffieHellmanCalcSharedKey.s: DiffieHellmanCalcSharedKey.cpp.s

.PHONY : DiffieHellmanCalcSharedKey.s

# target to generate assembly for a file
DiffieHellmanCalcSharedKey.cpp.s:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/DiffieHellmanCalcSharedKey.cpp.s
.PHONY : DiffieHellmanCalcSharedKey.cpp.s

DiffieHellmanInit.o: DiffieHellmanInit.cpp.o

.PHONY : DiffieHellmanInit.o

# target to build an object file
DiffieHellmanInit.cpp.o:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/DiffieHellmanInit.cpp.o
.PHONY : DiffieHellmanInit.cpp.o

DiffieHellmanInit.i: DiffieHellmanInit.cpp.i

.PHONY : DiffieHellmanInit.i

# target to preprocess a source file
DiffieHellmanInit.cpp.i:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/DiffieHellmanInit.cpp.i
.PHONY : DiffieHellmanInit.cpp.i

DiffieHellmanInit.s: DiffieHellmanInit.cpp.s

.PHONY : DiffieHellmanInit.s

# target to generate assembly for a file
DiffieHellmanInit.cpp.s:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/DiffieHellmanInit.cpp.s
.PHONY : DiffieHellmanInit.cpp.s

DiffieHellmanWrapper.o: DiffieHellmanWrapper.cpp.o

.PHONY : DiffieHellmanWrapper.o

# target to build an object file
DiffieHellmanWrapper.cpp.o:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/DiffieHellmanWrapper.cpp.o
.PHONY : DiffieHellmanWrapper.cpp.o

DiffieHellmanWrapper.i: DiffieHellmanWrapper.cpp.i

.PHONY : DiffieHellmanWrapper.i

# target to preprocess a source file
DiffieHellmanWrapper.cpp.i:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/DiffieHellmanWrapper.cpp.i
.PHONY : DiffieHellmanWrapper.cpp.i

DiffieHellmanWrapper.s: DiffieHellmanWrapper.cpp.s

.PHONY : DiffieHellmanWrapper.s

# target to generate assembly for a file
DiffieHellmanWrapper.cpp.s:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/DiffieHellmanWrapper.cpp.s
.PHONY : DiffieHellmanWrapper.cpp.s

RequestQueue.o: RequestQueue.cpp.o

.PHONY : RequestQueue.o

# target to build an object file
RequestQueue.cpp.o:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/RequestQueue.cpp.o
.PHONY : RequestQueue.cpp.o

RequestQueue.i: RequestQueue.cpp.i

.PHONY : RequestQueue.i

# target to preprocess a source file
RequestQueue.cpp.i:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/RequestQueue.cpp.i
.PHONY : RequestQueue.cpp.i

RequestQueue.s: RequestQueue.cpp.s

.PHONY : RequestQueue.s

# target to generate assembly for a file
RequestQueue.cpp.s:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/RequestQueue.cpp.s
.PHONY : RequestQueue.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/client_common.dir/build.make CMakeFiles/client_common.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client_common"
	@echo "... AesEncoder.o"
	@echo "... AesEncoder.i"
	@echo "... AesEncoder.s"
	@echo "... Client.o"
	@echo "... Client.i"
	@echo "... Client.s"
	@echo "... Command.o"
	@echo "... Command.i"
	@echo "... Command.s"
	@echo "... Connection.o"
	@echo "... Connection.i"
	@echo "... Connection.s"
	@echo "... DiffieHellmanCalcSharedKey.o"
	@echo "... DiffieHellmanCalcSharedKey.i"
	@echo "... DiffieHellmanCalcSharedKey.s"
	@echo "... DiffieHellmanInit.o"
	@echo "... DiffieHellmanInit.i"
	@echo "... DiffieHellmanInit.s"
	@echo "... DiffieHellmanWrapper.o"
	@echo "... DiffieHellmanWrapper.i"
	@echo "... DiffieHellmanWrapper.s"
	@echo "... RequestQueue.o"
	@echo "... RequestQueue.i"
	@echo "... RequestQueue.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

